name: akashic
description: The one place for all your books!

publish_to: 'none' 

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  http: ^1.1.0
  shared_preferences: ^2.2.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
     - assets/profile.png
     - assets/akashic-book.png

  fonts:
    - family: Lily
      fonts:
        - asset: fonts/LilyScriptOne-Regular.ttf

    - family: Inter
      fonts:
        - asset: fonts/Inter-Light.ttf

    - family: Interbold
      fonts:
        - asset: fonts/Inter-SemiBold.ttf

    - family : InterB
      fonts:
        - asset: fonts/Inter-Bold.ttf
        
